### ISSUE TITLE
Got wrong information while inquire for the second time without refresh page.

### ISSUE THREAD

**Issue by eelQ** [JSNewbs/express_helper#2]
1. Select company, enter delivery code, enter. You would get the right information.
2. Do not close the page, select another company, input another delivery number,  enter.
3. You would get wrong information. --> Problem

**Comment by Zhgong** [comment]
Hello eelQ, 
I could not reproduce this issue. But another issue #5 was found while trying to reproduce this issue according the steps you've mentioned. #5 has been fixed. Could you please try again with the lastest version?

**Comment by kenshinji** [comment]
I think we should add the way of installing this extension without Chrome Web Store into README.md.

**Comment by eelQ** [comment]
Actually this issue #2 is a duplicated one with issue #5, you fixed it already? Good for you.

**Comment by Zhgong** [comment]
Issue #5 has already beendet fixed.:)

eelQ notifications@github.com schrieb am Sa. 12. Nov. 2016 um 12:34:

**Comment by kenshinji** [comment]
@eelQ @Zhgong so this issue could be closed? I think.
